SELECT T.FOOD_TYPE, T.REST_ID, T.REST_NAME, MAX(T.FAVORITES) AS FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FAV_ORDER
    FROM REST_INFO
) T
WHERE T.FAV_ORDER = '1'
GROUP BY T.FOOD_TYPE
ORDER BY T.FOOD_TYPE DESC