SELECT T2.USER_ID, T2.NICKNAME, CONCAT(T2.CITY, ' ', T2.STREET_ADDRESS1, ' ', T2.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(T2.TLNO, 1, 3), '-', SUBSTRING(T2.TLNO, 4, 4), '-', SUBSTRING(T2.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD T1 JOIN USED_GOODS_USER T2 ON T1.WRITER_ID = T2.USER_ID
GROUP BY USER_ID, NICKNAME
HAVING COUNT(T1.WRITER_ID) >= 3
ORDER BY USER_ID DESC