-- ANIMAL_OUTS에만 있고, ANIMAL_INS에는 없는 ANIMAL_ID, NAME
SELECT T2.ANIMAL_ID, T2.NAME
FROM ANIMAL_INS T1 RIGHT JOIN ANIMAL_OUTS T2 ON T1.ANIMAL_ID = T2.ANIMAL_ID
WHERE T1.ANIMAL_ID IS NULL
ORDER BY T2.ANIMAL_ID