-- T1에서 '거래완료' 상태, 가격
-- T2에서 '닉네임'
-- 조건 : 총 금액이 70만원 이상인 사람의 총 거래금액
SELECT T2.USER_ID AS USER_ID, T2.NICKNAME AS NICKNAME, SUM(T1.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD T1, USED_GOODS_USER T2
WHERE T1.WRITER_ID = T2.USER_ID AND T1.STATUS = 'DONE'
GROUP BY USER_ID
HAVING SUM(T1.PRICE) >= 700000
ORDER BY TOTAL_SALES