SELECT DISTINCT T2.EMP_NO, T2.EMP_NAME, 
    CASE
        WHEN AVG(T3.SCORE) >= 96 THEN 'S'
        WHEN AVG(T3.SCORE) >= 90 THEN 'A'
        WHEN AVG(T3.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE, 
    CASE
        WHEN AVG(T3.SCORE) >= 96 THEN T2.SAL * 0.2
        WHEN AVG(T3.SCORE) >= 90 THEN T2.SAL * 0.15
        WHEN AVG(T3.SCORE) >= 80 THEN T2.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_DEPARTMENT T1, HR_EMPLOYEES T2, HR_GRADE T3
WHERE T1.DEPT_ID = T2.DEPT_ID AND T2.EMP_NO = T3.EMP_NO
GROUP BY T2.EMP_NO
ORDER BY T2.EMP_NO ASC