SELECT T1.DEPT_ID AS DEPT_ID, T1.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(T2.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT T1 JOIN HR_EMPLOYEES T2 ON T1.DEPT_ID = T2.DEPT_ID
GROUP BY DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC