SELECT T.CATEGORY, MAX(T.PRICE) AS MAX_PRICE, T.PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
    FROM FOOD_PRODUCT
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
    AND PRICE IS NOT NULL
) T
WHERE RN = 1
GROUP BY CATEGORY
ORDER BY PRICE DESC